# Site settings
title: Mehackit Media Art Workshop with Processing
email: hello@mehackit.org
description: Creative programming workshop with Processing
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://sonic-pi.mehackit.org" # the base hostname & protocol for your site
url : "http://127.0.0.1:4000"
twitter_username: mehackit
github_username:  ohss

# Build settings
markdown: kramdown

collections:
  exercises:
    output: true